### PR TITLE
Bump `faster-hex` to `v0.8.2`

### PR DESCRIPTION
**Pull request by eval-exec**
We need to publish a new version of `faster-hex`

### CODE REVIEW

**Comment by eval-exec** [comment]
CI failed, https://github.com/nervosnetwork/faster-hex/pull/41 fixed that.

**Comment by eval-exec** [comment]
Rebased on master.

**Review by zhangsoledad — APPROVED** [review]

**Comment by l-wegner** [comment]
Hi,

I just wanted to mention, that this version contains kind of a breaking change by extending the error enum.

This crate does not compile anymore: https://crates.io/crates/gix-hash/0.13.1/dependencies.

Maybe releasing it as v0.9.0 is better and recreate v0.8.1?

**Comment by eval-exec** [comment]
> Hi,
> 
> I just wanted to mention, that this version contains kind of a breaking change by extending the error enum.
> 
> This crate does not compile anymore: https://crates.io/crates/gix-hash/0.13.1/dependencies.
> 
> Maybe releasing it as v0.9.0 is better and recreate v0.8.1?

Sorry, I have yanked `v0.8.2`, going to release `v0.9.0`

**Comment by l-wegner** [comment]
Thank you very much. Solved my issue.

**Pull request merged**
