### PR TITLE
add support for defmt log using a new feature

### PR DESCRIPTION
**Pull request by Georges760**

### CODE REVIEW

**Comment by eval-exec** [comment]
Hello @Georges760 Will this PR cause performance loss?

**Comment by eval-exec** [comment]
I exeucted `cargo bench` on master, then execute `cargo bench` again on your PR, it seems that some bench case report performance loss about 20%

**Comment by Georges760** [comment]
Nope it is just a formatting for debug purpose, so in production should not be enable.

**Comment by Georges760** [comment]
It is like the Serde derive, just an additional feature optional

**Review by eval-exec — APPROVED** [review]

**Comment by eval-exec** [comment]
> Nope it is just a formatting for debug purpose, so in production should not be enable.

OK, it's seem that `cargo bench`'s result is not stable.

**Review by zhangsoledad — APPROVED** [review]

**Pull request merged**
